import SwaggerJsDoc from "swagger-jsdoc";

const definition = {
  // Like the one described here: https://swagger.io/specification/#infoObject
  info: {
    description: "Express API with autogenerated Swagger Documentation",
    title: "NS8 Code Challenge API",
    version: "0.0.1",
  },
  host: 'localhost:3000',
  basePath: '/',
};

const options = {
  // List of files to be processed. You can also set globs "./routes/*.js"
  apis: [ "**/*.ts" ],

  swaggerDefinition: definition,

};

export const specs = SwaggerJsDoc(options);
